version: '3.7'

x-build: &build
  context: .
  dockerfile: dockerfiles/dev.dockerfile

x-service: &service
  build: *build
  volumes:
    - ./src:/src
    - ./data:/data
  working_dir: /src

services:
  backup_extract:
    <<: *service
    command: python backup_extract.py

  gen_final:
    <<: *service
    command: python gen_final.py

  delete:
    <<: *service
    env_file:
      - twitter.env
    command: python delete.py
